### ISSUE TITLE
There is no input signal in modelsim

### ISSUE THREAD

**Issue by AdmsLCW** [pulp-platform/pulpino#396]
I have successfully printed hello world but I can't observe the input signal and the signal  I want because of optimization, and when I turn off optimization, modelsim doesn't work, how can I fix this.
The modelsim version is modelsim-se-2020.4

**Comment by wmhaikal00** [comment]
Hi AdmsLCW

May I know how did you to compile the RTL using the modelsim-se-2020.4 ? I'm trying to compile, however I met with no rule to make target error.

**Comment by AdmsLCW** [comment]
No target error may be happened in cmake，you should check the version of cmake.

**Comment by AdmsLCW** [comment]
In order to solve this problem, I run the pulpino by vcs. And now I can see the waveform which i need.

**Comment by sharad2000** [comment]
Hi @AdmsLCW actually I am not able to get Hello world, and I am also using vcs. Can you Please tell me how I can debug this?
Thanks

**Comment by AdmsLCW** [comment]
Emm, it's been so long that I forgot the details. First, make sure the file is complete, then modify the header file path, or load it in the script. Finally, compile the files in the order of startup in the original project and start the simulation. Maybe I will upload the vcs version of the environment later when I'm free.

**Comment by sharad2000** [comment]
Hi @AdmsLCW actually I have done all of the required steps which were given in the readme part, and I have also generated the .slm files which were needed for instruction memory data and data memory data for Helloworld.c code.

Now I am simulating it and also gotten the waveform through verdi but I am just not able to find out what is the issue is as I am not able to see hello world.

I sincerely request you to please share any possible data that you can at your earliest convenience.
Thank you so much for your help and support.

**Comment by AdmsLCW** [comment]
Did you save the output content to a file？

**Comment by sharad2000** [comment]
Hi @AdmsLCW, this is the trace_core.log file that is being generated.      

It is only a portion of the file.

Time          Cycles PC       Instr    Mnemonic
         15603280000          390065 00000080 00108117 auipc            x2, 0x108000         x2=00108080
         15603320000          390066 00000084 f8010113 addi             x2, x2, -128         x2=00108000  x2:00108080
         15603360000          390067 00000088 00100d17 auipc            x26, 0x100000       x26=00100088
         15603400000          390068 0000008c 158d0d13 addi             x26, x26, 344       x26=001001e0 x26:00100088
         15603440000          390069 00000090 00100d97 auipc            x27, 0x100000       x27=00100090
         15603480000          390070 00000094 150d8d93 addi             x27, x27, 336       x27=001001e0 x27:00100090
         15603520000          390071 00000098 01bd5863 bge              x26, x27, 16        x26:001001e0 x27:001001e0
         15603640000          390074 000000a8 246000ef jal              x1, 582              x1=000000ac
         15603720000          390076 000002ee ff010113 addi             x2, x2, -16          x2=00107ff0  x2:00108000
         15603760000          390077 000002f0 00812423 sw               x8, 8(x2)            x8:xxxxxxxx  x2:00107ff0  PA:00107ff8
         15603800000          390078 000002f2 00912223 sw               x9, 4(x2)            x9:xxxxxxxx  x2:00107ff0  PA:00107ff4
         15603840000          390079 000002f4 00100437 lui              x8, 0x100000         x8=00100000
         15603880000          390080 000002f8 001004b7 lui              x9, 0x100000         x9=00100000
         15603920000          390081 000002fc 1d048793 addi             x15, x9, 464        x15=001001d0  x9:00100000
         15603960000          390082 00000300 1d040413 addi             x8, x8, 464          x8=001001d0  x8:00100000
         15604000000          390083 00000304 40f40433 sub              x8, x8, x15          x8=00000000  x8:001001d0 x15:001001d0
         15604040000          390084 00000306 01212023 sw               x18, 0(x2)          x18:xxxxxxxx  x2:00107ff0  PA:00107ff0
         15604080000          390085 00000308 00112623 sw               x1, 12(x2)           x1:000000ac  x2:00107ff0  PA:00107ffc
         15604120000          390086 0000030a 40245413 srai             x8, x8, 0x402        x8=00000000  x8:00000000
         15604160000          390087 0000030c 1d048493 addi             x9, x9, 464          x9=001001d0  x9:00100000
         15604200000          390088 00000310 00000913 addi             x18, x0, 0          x18=00000000
         15604240000          390089 00000312 02891863 bne              x18, x8, 48         x18:00000000  x8:00000000
         15604280000          390090 00000316 001004b7 lui              x9, 0x100000         x9=00100000
         15604320000          390091 0000031a fbbff0ef jal              x1, -70              x1=0000031c
         15604400000          390093 000002d4 00008067 jalr             x0, x1, 0            x1:0000031c
         15604480000          390095 0000031c 00100437 lui              x8, 0x100000         x8=00100000
         15604520000          390096 00000320 1d048793 addi             x15, x9, 464        x15=001001d0  x9:00100000
         15604560000          390097 00000324 1d040413 addi             x8, x8, 464          x8=001001d0  x8:00100000
         15604600000          390098 00000328 40f40433 sub              x8, x8, x15          x8=00000000  x8:001001d0 x15:001001d0
         15604640000          390099 0000032a 40245413 srai             x8, x8, 0x402        x8=00000000  x8:00000000
         15604680000          390100 0000032c 1d048493 addi             x9, x9, 464          x9=001001d0  x9:00100000
         15604720000          390101 00000330 00000913 addi             x18, x0, 0          x18=00000000
         15604760000          390102 00000332 00891d63 bne              x18, x8, 26         x18:00000000  x8:00000000
         15604800000          390103 00000336 00c12083 lw               x1, 12(x2)           x1=000000ac  x2:00107ff0  PA:00107ffc

**Comment by sharad2000** [comment]
@AdmsLCW 

After running ./simv command this is showing 

Using MEMLOAD method: PRELOAD
Using      ri5cy core
*Verdi* Loading libsscore_vcsmx202409.so
FSDB Dumper for VCS-MX, Release Verdi_W-2024.09-SP2, Linux x86_64/64bit, 03/03/2025
(C) 1996 - 2025 by Synopsys, Inc.
*Verdi* : Create FSDB file 'result.fsdb'
*Verdi* : Begin traversing the scope (tb), layer (0).
*Verdi* : End of traversing.
*Verdi* : fsdbDumpon - All FSDB files at 0 ps.
[SPI] Enabling QPI mode
[adv_dbg_if] AXI4 WRITE         32 burst @1a107008 for           4 bytes.
Preloading memory
Preloading instruction memory from slm_files/l2_stim.slm
Preloading data memory from slm_files/tcdm_bank0.slm
[TRACER] Output filename is: trace_core_00_0.log
RX string:                                                                                                                                                                                                                                                                 
[SPI] Received 00000000
[SPI] Test OK

**Comment by sharad2000** [comment]
Hi @AdmsLCW 


I am currently working on extending the PULPino platform and integrating it with additional IPs, including a UART module that adheres strictly to the AMBA APB protocol specification. During this process, I noticed a protocol compliance issue in the existing APB implementation within PULPino, specifically in the way the UART peripheral is accessed.

In the current PULPino design, the UART interface appears to operate using only the Access phase of the APB protocol (i.e., PSEL=1, PENABLE=1). The Setup phase (PSEL=1, PENABLE=0), which is an essential part of the APB specification, is not utilized or enforced.
Because of this, the peripheral logic directly reacts to PSEL and PENABLE both being high, without validating if the correct transition from the setup to access phase has occurred.

Read and write operations may not behave as expected, especially when used with verified third-party IPs.

A possible solution might be to Introduce a simple FSM or state-tracking logic at the peripheral interface level that distinguishes between setup and access phases.

Please let me know your thoughts on this, and whether such enhancements would be considered for future updates.


Thank you for listening.
