### ISSUE TITLE
make vcompile: No rule to make target

### ISSUE THREAD

**Issue by wmhaikal00** [pulp-platform/pulpino#397]
Hello and hi everyone ! 

I'm trying to compile the RTL. However, i met with this issue. Can anyone advice me on what should i do to compile the RTL successfully ? Your help is much appreciated

![pulpino github problem](https://user-images.githubusercontent.com/129572647/232953531-af23e1d6-5425-4490-a06c-436303035488.png)

**Comment by AdmsLCW** [comment]
Select a configuration file about riscv, put it in the build folder, and run the configuration file in the terminal (because the file is executable). When the configuration is complete, enter make vcompile.

**Comment by wmhaikal00** [comment]
Can you give me the specific name of the configuration file? I don't quite get it. Thanks!

**Comment by AdmsLCW** [comment]
My choice is cmake_configure.riscv.gc.sh

**Comment by wmhaikal00** [comment]
![image](https://user-images.githubusercontent.com/129572647/236083838-12159a14-4fbd-419a-b5f3-f9c62a0605e7.png)

**Comment by wmhaikal00** [comment]
I tried to run the cmake_configure.riscv.gcc.sh as you suggested. But it seems the system is unknown to cmake. Thus it unable to compile simple test program. My current version of cmake is 3.10.2. 

![image](https://user-images.githubusercontent.com/129572647/236084656-6b3b4bac-8964-4070-a637-a2257ae36b50.png)

Do you have any suggestions on how should i fix this problem ?

**Comment by AdmsLCW** [comment]
The problem is that you do not have the cross-compiler installed, and the configuration file cannot find the cross-compiler. You need to download the cross-compiler (https://github.com/pulp-platform/ri5cy_gnu_toolchain). If you have installed the cross-compiler and still cannot find the cross-compiler, you just did not add the path of the cross-compiler to the environment variable in the user. If you have trouble compiling the cross-compiler, try compiling with gcc version 5.2 or 5.20 (I don't remember exactly).
