### ISSUE TITLE
pulpino/sw/apps/riscv_tests/testCSR/testCSR.c:153: Error: Instruction csrrw requires absolute expression

### ISSUE THREAD

**Issue by berndca** [pulp-platform/pulpino#6]
I have run into problems building the sw.

I'm getting the error message:

    Assembler messages:
    pulpino/sw/apps/riscv_tests/testCSR/testCSR.c:153: Error: Instruction csrrw requires absolute expression
    pulpino/sw/apps/riscv_tests/testCSR/testCSR.c:153: Error: Instruction csrr requires absolute expression

I'm using https://github.com/riscv/riscv-gnu-toolchainriscv-gnu-toolchain configured with 

    ./configure --prefix=/opt/riscv --with-xlen=32

I did not make any changes to cmake_configure.riscv.gcc.sh 

Please advise.
Thanks, Bernd

**Comment by atraber** [comment]
I don't know what the issues is here, but it is definitely related to the inline assembly code that we use to check if our CSR registers are working properly.

I'm currently compiling the latest riscv-gnu-toolchain to see if I can reproduce the issue, since our toolchain compiles this piece of code well and also the riscv-gnu-toolchain version I'm having locally works well.

In any case, if this is the only issue that you are seeing, you can also just ignore it. Compiling testCSR is not vital for PULPino

**Comment by berndca** [comment]
Thanks for the reply. Could you please confirm that --with-xlen=32 is the only option required for building the pulpino tool chain?

**Comment by atraber** [comment]
Yes, at least it is what we were using

**Comment by atraber** [comment]
It seems that the privilege specs have been changed. I checked the latest toolchain and there the mcpuid CSR register does no longer exist and the mimpid and mhartid registers have other addresses. So it is not surprising that this gives compile errors.

I have changed our local tests to still compile, but assume the old values for those registers, but probably we will change them for the future as soon as there is a stable spec available.
