### ISSUE TITLE
ETH version compiler

### ISSUE THREAD

**Issue by Erik-Chen** [pulp-platform/pulpino#9]
Hello
   In the readme, there are two versions of compiler we can use for PULPino. I want to build the ETH version to use the full ISA on PULPino. Where can I get the information? Thank you!
Erik

**Comment by Erik-Chen** [comment]
I found it at https://iis.ee.ethz.ch/~haugoug/pulp/

**Comment by ztbztb12345** [comment]
Hello
How to register at this website? It needs to log in. Thank you!

**Comment by Erik-Chen** [comment]
Hi,
The website is locked now. I am not the officials. I already sent an email to them.

**Comment by atraber** [comment]
Hi guys,

We protected the website with a password since it was never intended to be open as it contains our internal resources.
We want to completely open-source our compiler and everything related to it as soon as possible, but as you can imagine this is not so simple since you need to clean up code, add some documentation, ...

You can find our timeline here: http://www.pulp-platform.org/release-plan/

If everything goes according to plan, we can share it within a couple of weeks :-)

**Comment by ztbztb12345** [comment]
Thank you very much. ^_^
